Fix CI and add reports

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,23 +11,23 @@ on:
 
 permissions:
   contents: read
+  checks: write
 
 jobs:
-  prepare:
+  qa:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
       with:
-        repository: JimmyTournemaine/ha-core
-        path: ${{ github.workspace }}/ha-core
+        path: ./ha-knocki
     - uses: actions/checkout@v4
       with:
-        path: ${{ github.workspace }}/ha-knocki
+        repository: JimmyTournemaine/ha-core
+        path: ./ha-core
     - name: Merge ha-knocki in core
       run: |
-        ln -s "${{ github.workspace }}/ha-knocki/knocki" "${{ github.workspace }}/ha-core/homeassistant/components/knocki"
-        ln -s "${{ github.workspace }}/ha-knocki/tests" "${{ github.workspace }}/ha-core/tests/components/knocki"
-      # ln -s "${{ github.workspace }}/ha-knocki/blueprints/automation" "${{ github.workspace }}/ha-core/config/blueprints/automation/knocki"
+        ln -s "$(pwd)/ha-knocki/knocki" "$(pwd)/ha-core/homeassistant/components/knocki"
+        ln -s "$(pwd)/ha-knocki/tests" "$(pwd)/ha-core/tests/components/knocki"
     - name: Set up Python 3.12
       uses: actions/setup-python@v3
       with:
@@ -35,27 +35,34 @@ jobs:
     - name: Run HA setup script
       run: |
         script/setup
-      working-directory: ${{ github.workspace }}/ha-core
-    #- name: Install test dependencies
-    #  run: |
-    #    apt-get install -y python-dev pkg-config
-    #    apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
-    #    source venv/bin/activate
-    #    pip3 install -r requirements_test_all.txt
-    #  working-directory: ${{ github.workspace }}/ha-core
-    #- name: Test with pytest
-    #  run: |
-    #    source venv/bin/activate
-    #    pytest tests/components/knocki --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
-    #  working-directory: ${{ github.workspace }}/ha-core
-  
-  lint:
-    runs-on: ubuntu-latest
-    needs: prepare
-    steps:
+      working-directory: ./ha-core
+
     - name: Lint with Ruff
       run: |
         source venv/bin/activate
         ruff --output-format=github ./homeassistant/components/knocki ./tests/components/knocki
-      working-directory: ${{ github.workspace }}/ha-core
+      working-directory: ./ha-core
       continue-on-error: true
+    - name: Install test dependencies
+      run: |
+        source venv/bin/activate
+        pip3 install -r requirements_test.txt
+        pip3 install sqlalchemy
+        pip3 install $(cat requirements_all.txt | grep -e ffmpeg== -e zeroconf==)
+      working-directory: ./ha-core
+    - name: Test with pytest
+      run: |
+        source venv/bin/activate
+        pytest tests/components/knocki --doctest-modules --junitxml=junit/test-results.xml --cov=./homeassistant/components/knocki --cov-report=xml
+      working-directory: ./ha-core
+    - name: Publish test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: ./ha-core/junit/test-results.xml
+        follow_symlink: true
+    - name: Publish coverage report
+      uses: MishaKav/pytest-coverage-comment@main
+      with:
+        pytest-coverage-path: ./pytest-coverage.txt
+        junitxml-path: ./ha-core/coverage.xml
