:sparles: Mypy workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,6 +71,36 @@ jobs:
             | sed 's|homeassistant/components/knocki|knocki|'
           exit $ruff_exitcode
         working-directory: ./ha-core
+      - name: Lint with Mypy
+        run: |
+          format_mypy_error() {
+              local file_path=$1
+              local line_number=$2
+              local message=$3
+              local error_type=${4:-"error"}
+              echo "::${error_type} file=${file_path},line=${line_number},endLine=${line_number},title=${message}::${message}"
+          }
+          parse_mypy_output() {
+              local mypy_output=$1
+              local errors=()
+              while IFS= read -r line; do
+                  if [[ $line =~ ^(.*):([0-9]+): (warning|error): (.*)$ ]]; then
+                      file_path="${BASH_REMATCH[1]}"
+                      line_number="${BASH_REMATCH[2]}"
+                      error_type="${BASH_REMATCH[3]}"
+                      message="${BASH_REMATCH[4]}"
+                      errors+=("$(format_mypy_error "$file_path" "$line_number" "$message" "$error_type")")
+                  fi
+              done <<< "$mypy_output"
+              printf "%s\n" "${errors[@]}"
+          }
+          set +e
+          mypy_output=$(mypy homeassistant/components/knocki tests/components/knocki)
+          mypy_exitcode=$?
+          formatted_errors=$(parse_mypy_output "$mypy_output")
+          echo "$formatted_errors"
+          exit $mypy_exitcode
+        working-directory: ./ha-core
       - name: Test with pytest
         if: success() || failure()
         run: |
